version: "3.8"

services:
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
      - ./output:/app/output
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./config:/app/config
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - PYTHONPATH=/app
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:9090/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  monitoring:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - bot
